tgt_entretien:
    resource: "@TGTBundle/Controller/EntretienController.php"
    type:     annotation

tgt_contrat:
    resource: "@TGTBundle/Controller/ContratController.php"
    type:     annotation

tgt_candidat:
    resource: "@TGTBundle/Controller/CandidatController.php"
    type:     annotation

tgt:
    resource: "@TGTBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
