<?php

namespace Proxies\__CG__\TGTBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidat extends \TGTBundle\Entity\Candidat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id_casting', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id_entretient', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'nomC', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'cinCondidat', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'cv', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'motivation', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'mailaddress', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'tel'];
        }

        return ['__isInitialized__', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id_casting', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'id_entretient', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'nomC', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'cinCondidat', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'cv', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'motivation', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'mailaddress', '' . "\0" . 'TGTBundle\\Entity\\Candidat' . "\0" . 'tel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCasting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCasting', []);

        return parent::getIdCasting();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCasting($id_casting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCasting', [$id_casting]);

        return parent::setIdCasting($id_casting);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEntretient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEntretient', []);

        return parent::getIdEntretient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEntretient($id_entretient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEntretient', [$id_entretient]);

        return parent::setIdEntretient($id_entretient);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomC', []);

        return parent::getNomC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomC($nomC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomC', [$nomC]);

        return parent::setNomC($nomC);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinCondidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinCondidat', []);

        return parent::getCinCondidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinCondidat($cinCondidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinCondidat', [$cinCondidat]);

        return parent::setCinCondidat($cinCondidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCv', []);

        return parent::getCv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCv($cv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCv', [$cv]);

        return parent::setCv($cv);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivation', []);

        return parent::getMotivation();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivation($motivation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivation', [$motivation]);

        return parent::setMotivation($motivation);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailaddress', []);

        return parent::getMailaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailaddress($mailaddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailaddress', [$mailaddress]);

        return parent::setMailaddress($mailaddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
