<?php

namespace TGTBundle\Repository;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends \Doctrine\ORM\EntityRepository
{
}
