<?php

namespace TGTBundle\Repository;

/**
 * OrganisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
