<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\FullCalendarListener' shared autowired service.

return $this->services['App\\EventListener\\FullCalendarListener'] = new \App\EventListener\FullCalendarListener();
