<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1fmnh3r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1fmnh3r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1fmnh3r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1fmnh3r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1fmnh3r\appDevDebugProjectContainer([
    'container.build_hash' => '1fmnh3r',
    'container.build_id' => '397c4a30',
    'container.build_time' => 1581667976,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1fmnh3r');
