<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsjiauv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsjiauv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWsjiauv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWsjiauv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWsjiauv\appDevDebugProjectContainer([
    'container.build_hash' => 'Wsjiauv',
    'container.build_id' => '289acb14',
    'container.build_time' => 1582212752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsjiauv');
